version: "2.1"
services:
    identity:
        image: docker.snapshot.travel:5000/snapshot/nonpms_integrations:latest
        depends_on:
            - postgresql
            - activemq
        ports:
            - "18081:18081"
            - "18080:18080"
        environment:
            ARTIFACT: "IdentityModule-1.0.jar"
            SPRING_PROFILE: identity
        networks:
            - main
    ## Please note that springboot container uses tmp a lot, so you'll need to
    ## have a dedicated folder in your filesystem for container's /tmp 
    ## On the systems with selinux enforced this folder must have a container_file_t label:
    ## > semanage fcontext -a -t container_file_t "/path/to/tmp(/*)"
    ## > restorecon -R /path/to/tmp
    ## Please adapt the following volume lines to point to the correct
    ## places where:
    ## 1. your docker_shared folder is
    ## 2. dedicated folder for container's tmp
    ## 3. Folder where *.properties file resides
        volumes:
            - $COREQA_BASE/redeployDP/docker_shared:/data:ro
            - $BASE_FOLDER/shared:/tmp:rw
            - $COREQA_BASE/redeployDP/docker_shared/tomcat/config:/opt/integrations/config:ro
    ## The same applies to all non-pms-integration images
    postgresql:
        image: postgres:9.6
        environment:
            - POSTGRES_PASSWORD=secret
        volumes:
            - $COREQA_BASE/redeployDP/docker_shared/sql:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
        networks:
            - main
    activemq:
        image: rmohr/activemq:5.14.3
        ports:
          - 61617:61616
          - 8162:8161
        networks:
            - main
    keycloak:
        image: snapshothub/dp-keycloak:master-56
        ports:
            - 8081:8080
            - 9991:9990
            - 8788:8787
        volumes:
            - $COREQA_BASE/redeployDP/docker_shared/keycloak:/opt/keycloak
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - KEYCLOAK_LOGLEVEL=DEBUG
            - POSTGRES_PORT_5432_TCP_ADDR=postgresql
            - POSTGRES_PORT_5432_TCP_PORT=5432
            - POSTGRES_DATABASE=keycloak
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secret
            - IDENTITY_API_URI=http://identity:18080/api
            - IDENTITY_APPLICATION_VERSION_ID=04000000-0000-4444-8888-000000000000
            - IDENTITY_USER_ID=0b000000-0000-4444-8888-000000000000
        depends_on:
            - postgresql
        networks:
            - main
    redis:
        image: redis:4
        ports:
          - 6380:6379
        volumes:
          - ./redis:/data
        networks:
          - main
    nginx:
        image: snapshothub/dp-nginx:master-64
        ports:
            - 81:80
        volumes:
            - $COREQA_BASE/redeployDP/docker_shared/nginx:/usr/local/openresty/nginx/conf.d
        depends_on:
            - identity
            - keycloak
            - redis
        networks:
            - main
networks:
    main:
