version: "2.1"
services:
    identity:
        image: docker.snapshot.travel:5000/snapshot/nonpms_integrations:latest
        depends_on:
            - postgresql
            - activemq
        ports:
            - "18081:18081"
            - "18080:18080"
        environment:
            ARTIFACT: "IdentityModule-1.0.jar"
            SPRING_PROFILE: identity
        networks:
            - main
    ## Please note that springboot container uses tmp a lot, so you'll need to
    ## have a dedicated folder in your filesystem for container's /tmp 
    ## On the systems with selinux enforced this folder must have a container_file_t label:
    ## > semanage fcontext -a -t container_file_t "/path/to/tmp(/*)"
    ## > restorecon -R /path/to/tmp
    ## Please adapt the following volume lines to point to the correct
    ## places where:
    ## 1. your docker_shared folder is
    ## 2. dedicated folder for container's tmp
    ## 3. Folder where *.properties file resides
        volumes:
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared:/data:ro
            - $BASE_FOLDER/shared:/tmp:rw
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared/tomcat/config:/opt/integrations/config:ro
    ## The same applies to all non-pms-integration images
 
    postgresql:
        image: postgres:9.6
        environment:
            - POSTGRES_PASSWORD=secret
        volumes:
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared/sql:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
        networks:
            - main
    activemq:
        image: rmohr/activemq:5.14.3
        ports:
          - 61617:61616
          - 8162:8161
        networks:
            - main
networks:
    main:
