version: "2.1"
services:
    db_migrator:
        image: docker.snapshot.travel:5000/snapshot/db_migrator:latest
        depends_on: 
            - mariadb
        environment:
            DB_PASSWORD: root
        networks:
            - main

    identity:
        image: docker.snapshot.travel:5000/snapshot/nonpms_integrations:latest
        depends_on:
            - postgresql
            - activemq
        ports:
            - "18081:18081"
            - "18080:18080"
        environment:
            ARTIFACT: "IdentityModule-1.0.jar"
            SPRING_PROFILE: identity
        networks:
            - main
    ## Please note that springboot container uses tmp a lot, so you'll need to
    ## have a dedicated folder in your filesystem for container's /tmp 
    ## On the systems with selinux enforced this folder must have a container_file_t label:
    ## > semanage fcontext -a -t container_file_t "/path/to/tmp(/*)"
    ## > restorecon -R /path/to/tmp
    ## Please adapt the following volume lines to point to the correct
    ## places where:
    ## 1. your docker_shared folder is
    ## 2. dedicated folder for container's tmp
    ## 3. Folder where *.properties file resides
        volumes:
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared:/data:ro
            - $BASE_FOLDER/shared:/tmp:rw
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared/tomcat/config:/opt/integrations/config:ro
    ## The same applies to all non-pms-integration images
    twitter_api:
        image: docker.snapshot.travel:5000/snapshot/nonpms_integrations:latest
        depends_on:
            - mariadb
            - activemq
            - mongodb
            - identity
        ports:
            - "48080:48080"
            - "48081:48081"
        environment:
            ARTIFACT: "TwitterAnalyticsApi-1.0-SNAPSHOT.jar"
            SPRING_PROFILE: analytics,twitter
        networks:
            - main
        volumes:
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared:/data:ro
            - $BASE_FOLDER/shared:/tmp:rw
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared/tomcat/config:/opt/integrations/config:ro
     
    instagram_api:
        image: docker.snapshot.travel:5000/snapshot/nonpms_integrations:latest
        depends_on:
            - mariadb
            - activemq
            - mongodb
            - identity
        ports:
            - "38080:38080"
            - "38081:38081"
        environment:
            ARTIFACT: "InstagramAnalyticsApi-1.0-SNAPSHOT.jar"
            SPRING_PROFILE: analytics,instagram
        networks:
            - main
        volumes:
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared:/data:ro
            - $BASE_FOLDER/shared:/tmp:rw
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared/tomcat/config:/opt/integrations/config:ro

    google_api:
        image: docker.snapshot.travel:5000/snapshot/nonpms_integrations:latest
        depends_on:
            - mariadb
            - activemq
            - mongodb
            - identity
        ports:
            - "28080:28080"
            - "28081:28081"
        environment:
            ARTIFACT: "GoogleAnalyticsApi-1.0-SNAPSHOT.jar"
            SPRING_PROFILE: analytics,googleapi
        networks:
            - main
        volumes:
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared:/data:ro
            - $BASE_FOLDER/shared:/tmp:rw
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared/tomcat/config:/opt/integrations/config:ro

    facebook_api:
        image: docker.snapshot.travel:5000/snapshot/nonpms_integrations:latest
        depends_on:
            - mariadb
            - activemq
            - mongodb
            - identity
        ports:
            - "58080:58080"
            - "58081:58081"
        environment:
            ARTIFACT: "FacebookAnalyticsApi-1.0-SNAPSHOT.jar"
            SPRING_PROFILE: analytics,facebook
        networks:
            - main
        volumes:
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared:/data:ro
            - $BASE_FOLDER/shared:/tmp:rw
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared/tomcat/config:/opt/integrations/config:ro

    socialmedia_api:
        image: docker.snapshot.travel:5000/snapshot/nonpms_integrations:latest
        depends_on:
            - mariadb
            - activemq
            - mongodb
            - identity
        ports:
            - "15080:15080"
            - "15081:15081"
        environment:
            ARTIFACT: "SocialMediaApi-1.0-SNAPSHOT.jar"
            SPRING_PROFILE: analytics,socialmedia
        networks:
            - main
        volumes:
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared:/data:ro
            - $BASE_FOLDER/shared:/tmp:rw
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared/tomcat/config:/opt/integrations/config:ro

    rateshopper:
        image: docker.snapshot.travel:5000/snapshot/nonpms_integrations:latest
        depends_on:
            - mariadb
            - activemq
            - mongodb
            - identity
        ports:
            - "12080:12080"
            - "12081:12081"
        environment:
            ARTIFACT: "RateShopper-1.0-SNAPSHOT.jar"
            SPRING_PROFILE: analytics,rateshopper
        networks:
            - main
        volumes:
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared:/data:ro
            - $BASE_FOLDER/shared:/tmp:rw
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared/tomcat/config:/opt/integrations/config:ro

    review:
        image: docker.snapshot.travel:5000/snapshot/nonpms_integrations:latest
        depends_on:
            - mariadb
            - activemq
            - mongodb
            - identity
        ports:
            - "13080:13080"
            - "13081:13081"
        environment:
            ARTIFACT: "Review-1.0-SNAPSHOT.jar"
            SPRING_PROFILE: analytics,review
        networks:
            - main
        volumes:
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared:/data:ro
            - $BASE_FOLDER/shared:/tmp:rw
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared/tomcat/config:/opt/integrations/config:ro

    configuration:
        image: docker.snapshot.travel:5000/snapshot/nonpms_integrations:latest
        depends_on:
            - mariadb
            - activemq
            - mongodb
            - identity
        ports:
            - "11080:11080"
            - "11081:11081"
        environment:
            ARTIFACT: "configuration-1.0.jar"
            SPRING_PROFILE: configuration
        networks:
            - main
        volumes:
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared:/data:ro
            - $BASE_FOLDER/shared:/tmp:rw
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared/tomcat/config:/opt/integrations/config:ro
             
    mariadb:
        image: docker.io/mariadb:10.1.22
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - main

    postgresql:
        image: postgres:9.6
        environment:
            - POSTGRES_PASSWORD=secret
        volumes:
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared/sql:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
        networks:
            - main
    mongodb:
        image: docker.io/mongo:latest
        ports:
            - "27017:27017"
        networks:
            - main
    activemq:
        image: rmohr/activemq:5.14.3
        ports:
          - 61617:61616
          - 8162:8161
        networks:
            - main
    keycloak:
        image: snapshothub/dp-keycloak:master-56
        ports:
            - 8081:8080
            - 9991:9990
            - 8788:8787
        volumes:
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared/keycloak:/opt/keycloak
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - KEYCLOAK_LOGLEVEL=DEBUG
            - POSTGRES_PORT_5432_TCP_ADDR=postgresql
            - POSTGRES_PORT_5432_TCP_PORT=5432
            - POSTGRES_DATABASE=keycloak
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secret
            - IDENTITY_API_URI=http://identity:18080/api
            - IDENTITY_APPLICATION_VERSION_ID=04000000-0000-4444-8888-000000000000
            - IDENTITY_USER_ID=0b000000-0000-4444-8888-000000000000
        depends_on:
            - postgresql
        networks:
            - main
    redis:
        image: redis:4
        ports:
          - 6380:6379
        volumes:
          - ./redis:/data
        networks:
          - main
    nginx:
        image: snapshothub/dp-nginx:master-64
        ports:
            - 81:80
        volumes:
            - $BASE_FOLDER/dataplatformcoreqa/redeployDP/docker_shared/nginx:/usr/local/openresty/nginx/conf.d
        depends_on:
            - identity
            - keycloak
            - redis
        networks:
            - main
networks:
    main:
