delete from customer_property where customer_id in (select id from customer where name like 'CoreQA%');
delete from commercialsubscription where customer_id in (select id from customer where name like 'CoreQA%');
delete from rolepermission where application_id in (select id from application where name like 'CoreQA%');
delete from applicationpermission where application_id in (select id from application where name like 'CoreQA%');
delete from roleassignment where user_id in (select id from public."user" where username like 'CoreQA%');
delete from user_property where property_id in (select id from property where name like 'CoreQA%');
delete from user_propertyset where user_id in (select id from public."user" where username like 'CoreQA%');
delete from user_customer where customer_id in (select id from customer where name like 'CoreQA%');
delete from propertyset_property where property_id in (select id from property where name like 'CoreQA%');
delete from property where name like 'CoreQA%';
delete from propertyset where name like 'CoreQA%';
delete from customer where name like 'CoreQA%';
delete from user_partner where user_id in (select id from public."user" where username like 'CoreQA%');
delete from public."user" where username like 'CoreQA%';
delete from applicationversion where name like 'CoreQA%';
delete from role where name like 'CoreQA%';
delete from application where name like 'CoreQA%';
delete from partner where name like 'CoreQA%';
delete from address where line1 like 'CoreQA%';
