SET SESSION SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
LOAD DATA LOCAL INFILE 'dp.Dim_wp_source.tsv' INTO TABLE dp.Dim_wp_source FIELDS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'dp.Fact_facebook_cumulative.tsv' INTO TABLE dp.Fact_facebook_cumulative FIELDS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'dp.Fact_fb_post_stats.tsv' INTO TABLE dp.Fact_fb_post_stats FIELDS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'dp.Fact_instagram_daily.tsv' INTO TABLE dp.Fact_instagram_daily FIELDS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'dp.Fact_twitter_daily.tsv' INTO TABLE dp.Fact_twitter_daily FIELDS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'dp.Fact_twitter_tweets.tsv' INTO TABLE dp.Fact_twitter_tweets FIELDS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'dp.Fact_ta_daily.tsv' INTO TABLE dp.Fact_ta_daily FIELDS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'dp.Fact_ta_trip_type.tsv' INTO TABLE dp.Fact_ta_trip_type FIELDS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'dp.tripadvisor_geo_location.tsv' INTO TABLE dp.tripadvisor_geo_location FIELDS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'dp.Fact_web_performance_cumulative.tsv' INTO TABLE dp.Fact_web_performance_cumulative FIELDS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'dp.Fact_web_performance.tsv' INTO TABLE dp.Fact_web_performance FIELDS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'dp.tripadvisor_property.tsv' INTO TABLE dp.tripadvisor_property FIELDS TERMINATED BY '\t';
