SELECT PropertyID,
       ArrivalDay,
       OTBAggregationLogID,
       ReviewScore_HotelReviewScore,
       ReviewScore_CompetitorHotelReviewScore,
       DemandLevel_DemandLevelID,
       CompetitorBAR_CompetitorAverageBAR,
       CompetitorBAR_CompetitorRank,
       ChannelRank_ChannelRank,
       HotelBAR_BaseBARID,
       HotelBAR_CurrentSnapshotBARID,
       Group_GroupDefiniteRmNts,
       Group_GroupTentativeRmNts,
       Group_GroupOptionalRmNts,
       SnapshotForecast_RmNts,
       SnapshotForecast_Rate,
       SnapshotForecast_Revenue,
       OTBDef_RmNts,
       OTBDef_Revenue,
       OTBDef_DistributionCost,
       OTBTen_RmNts,
       OTBTen_Revenue,
       OTBTen_DistributionCost,
       Comments_ThisYear,
       ModifiedBy,
       ModificationTimestamp,
       Timeline_LevelID,
       Timeline_NextYearLevelID,
       WasManuallyUpdated,
       ChannelRank_NumberOfPropertiesInRegion,
       CompetitorBAR_NumberOfCompetitors,
       BudgetID,
       Timeline_BudgetLevelID,
       Timeline_BudgetNextYearLevelID,
       Budget_RmNts,
       Budget_Rate,
       Budget_Revenue,
       WasBudgetManuallyUpdated,
       ID,
       ReviewScore_HotelReviewScoreCumulative,
       ReviewScore_CompetitorHotelReviewScoreCumulative,
       CommissionTen_DynamicCommission,
       CommissionTen_FixedCommission,
       CommissionTen_FixedFees,
       CommissionDef_DynamicCommission,
       CommissionDef_FixedCommission,
       CommissionDef_FixedFees,
       OTBDef_NumberOfReservations,
       OTBTen_NumberOfReservations,
       CB_PropSupTY,
       CB_PropDemTY,
       CB_PropSupLY,
       CB_PropDemLY,
       CB_CompSupTY,
       CB_CompDemTY,
       CB_CompSupLY,
       CB_CompDemLY,
       CB_PropRevTY,
       CB_PropRevLY,
       CB_CompRevTY,
       CB_CompRevLY,
       RMSForecast_RmNts,
       RMSForecast_Revenue,
       RMSStrategy_OverbookingLevel,
       RMSStrategy_LastRoomValue,
       RMSStrategy_OverrideFlag,
       RMSStrategy_SystemUnconstrainedDemand,
       RMSStrategy_RMSUserBAR,
       RMSStrategy_RMSSystemBAR,
       ActiveBudget_RmNts,
       ActiveBudget_Revenue,
       RMSForecast_OverrideSnapshotForecast,
       Group_MinBARID,
       Group_MaxBARID,
       Group_BaseCeiling,
       CB_OccRank,
       CB_OccRankCompetitors,
       CB_ADRRank,
       CB_ADRRankCompetitors,
       CB_RevPARRank,
       CB_RevPARRankCompetitors,
       CompetitorBAR_HotelAverageBAR,
       CRSProduct_Restrictions,
       CRSRatePlan_Restrictions,
       CRSRoomType_Restrictions,
       BudgetComments_ThisYear,
       RMSStrategyRevGain_Rate,
       RMSStrategyRevGain_CompetitorRate,
       RMSStrategyRevGain_MarketPriceIndicator,
       RMSStrategyRevGain_BenchmarkRate,
       RMSStrategyRevGain_ValueIndexForAll,
       RMSStrategyRevGain_SupplyAvailable,
       RMSStrategyRevGain_SubscribersAvailableInventory,
       RMSStrategyRevGain_OptimumRate,
       RMSStrategyRevGain_RateChange,
       RMSStrategyRevGain_FinalAppliedRate,
       DistributedFixedCost
FROM dbo.FCSGridCurrentElements
where ModificationTimestamp > '2015-10-01';


SELECT count(ID)
FROM dbo.FCSGridCurrentElements
where ModificationTimestamp > '2015-09-01';


