#!/bin/sh

cat <<EOF>dp_bamboo_slave.properties
identity.baseURI=${BASE_URI}/v1
social_media.baseURI=${BASE_URI}/v1/social_media/analytics
twitter.baseURI=${BASE_URI}/v1/social_media/analytics/twitter
instagram.baseURI=${BASE_URI}/v1/social_media/analytics/instagram 
facebook.baseURI=${BASE_URI}/v1/social_media/analytics/facebook
configuration.baseURI=${BASE_URI}/v1/configuration
web_performance.baseURI=
authorization.baseURI=${BASE_URI}
identity_nginx.baseURI=${BASE_URI}/v1/identity
configuration_nginx.baseURI=${BASE_URI}/v1/configuration
rate_shopper.baseURI=${BASE_URI}/v1/rate_shopper
review.baseURI=${BASE_URI}/v1/review
http_request_log_level=ALL
http_response_log_level=ALL
http_response_log_status=
identity.db.connectionString=${IDENTITY_DB_STRING}
db.username=${DB_USER}
db.password=${DB_PASSWORD}
tti.db.connectionString=${TTI_DB_STRING}
tti.db.username=${TTI_DB_USERNAME}
tti.db.password=${TTI_DB_PASSWORD}
broker.url=${BROKER_URL}
broker.user=${BROKER_USER}
broker.password=${BROKER_PASSWORD}
keyCloakURI=${KEYCLOAK_URI}
keyCloakUsername=${KEYCLOAK_USER}
keyCloakPassword=${KEYCLOAK_PASSWORD}
testProperty.id=${PROPERTY_ID}
testCustomer.id=${CUSTOMER_ID}
testLocation.id=${LOCATION_ID}
client.id=${CLIENT_ID}
client.secret=${CLIENT_SECRET}
user.name=${API_USER_NAME}
user.password=${API_USER_PASSWORD}
EOF
